# Generated by Django 5.0.3 on 2024-03-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='instgram_link',
            new_name='instagram_link',
        ),
    ]
