# Generated by Django 5.0.3 on 2024-03-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_imag',
            field=models.ImageField(blank=True, null=True, upload_to='images/user'),
        ),
    ]
